// react/app/frontend/layouts/Layout.jsx
import { usePage } from "@inertiajs/react"
import { NativeTabs, NativePush } from "ruby_native/react"
import Navbar from "~/components/Navbar"
import Flash from "~/components/Flash"

export default function Layout({ children }) {
  const { user_signed_in, nativeApp } = usePage().props

  return (
    <div className="min-h-screen bg-gray-50">
      {user_signed_in && <><NativeTabs /><NativePush /></>}
      <Navbar />
      <div className={nativeApp ? "" : "pt-12"}>
        <Flash />
        <main className="max-w-lg mx-auto">{children}</main>
      </div>
    </div>
  )
}

// vue/app/frontend/layouts/Layout.vue
<script setup>
import { usePage } from "@inertiajs/vue3"
import { computed } from "vue"
import { NativeTabs, NativePush } from "ruby_native/vue"
import Navbar from "~/components/Navbar.vue"
import Flash from "~/components/Flash.vue"

const page = usePage()
const nativeApp = computed(() => page.props.nativeApp)
const userSignedIn = computed(() => page.props.user_signed_in)
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <template v-if="userSignedIn">
      <NativeTabs />
      <NativePush />
    </template>
    <Navbar />
    <div :class="nativeApp ? '' : 'pt-12'">
      <Flash />
      <main class="max-w-lg mx-auto">
        <slot />
      </main>
    </div>
  </div>
</template>
