// coffee/app/frontend/components/Flash.jsx
import { usePage } from "@inertiajs/react"
import { useState, useEffect } from "react"

export default function Flash() {
  const { flash } = usePage().props
  const [visible, setVisible] = useState(false)
  const message = flash?.notice || flash?.alert
  const isAlert = !!flash?.alert

  useEffect(() => {
    if (message) {
      setVisible(true)
      const timer = setTimeout(() => setVisible(false), 4000)
      return () => clearTimeout(timer)
    }
  }, [message])

  if (!visible || !message) return null

  return (
    <div className={`mx-4 mt-4 p-3 rounded-xl text-sm font-medium ${
      isAlert
        ? "bg-red-50 text-red-800 dark:bg-red-900/30 dark:text-red-300"
        : "bg-green-50 text-green-800 dark:bg-green-900/30 dark:text-green-300"
    }`}>
      {message}
    </div>
  )
}

// habits/app/frontend/components/Flash.vue
<script setup>
import { usePage } from "@inertiajs/vue3"
import { ref, watch, computed } from "vue"

const page = usePage()
const visible = ref(false)

const message = computed(() => page.props.flash?.notice || page.props.flash?.alert)
const isAlert = computed(() => !!page.props.flash?.alert)

watch(message, (val) => {
  if (val) {
    visible.value = true
    setTimeout(() => (visible.value = false), 4000)
  }
})
</script>

<template>
  <div
    v-if="visible && message"
    :class="[
      'px-4 py-3 text-sm font-medium',
      isAlert
        ? 'bg-red-50 text-red-800 border-b border-red-200'
        : 'bg-green-50 text-green-800 border-b border-green-200'
    ]"
  >
    <div class="max-w-lg mx-auto">{{ message }}</div>
  </div>
</template>
