// react/app/frontend/layouts/Layout.jsx
import { usePage } from "@inertiajs/react"
import Navbar from "~/components/Navbar"
import Flash from "~/components/Flash"

export default function Layout({ children }) {
  const { user_signed_in } = usePage().props

  return (
    <div className="min-h-screen bg-gray-50">
      {user_signed_in && <div data-native-tabs data-native-push hidden />}
      <Navbar />
      <div className="pt-12">
        <Flash />
        <main className="max-w-lg mx-auto">{children}</main>
      </div>
    </div>
  )
}

// habits/app/frontend/layouts/Layout.vue
<script setup>
import { usePage } from "@inertiajs/vue3"
import { computed } from "vue"
import Navbar from "~/components/Navbar.vue"
import Flash from "~/components/Flash.vue"

const page = usePage()
const userSignedIn = computed(() => page.props.user_signed_in)
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <template v-if="userSignedIn">
      <div data-native-tabs hidden></div>
    </template>
    <Navbar />
    <div class="pt-12 native-inset">
      <Flash />
      <main class="max-w-lg mx-auto">
        <slot />
      </main>
    </div>
  </div>
</template>
