// coffee/app/frontend/layouts/Layout.jsx
import { usePage } from "@inertiajs/react"
import { NativeTabs, NativePush } from "@ruby-native/react"
import Navbar from "~/components/Navbar"
import Flash from "~/components/Flash"

export default function Layout({ children }) {
  const { user_signed_in, nativeApp } = usePage().props

  return (
    <div className="min-h-screen bg-coffee-50 dark:bg-coffee-900">
      {user_signed_in && <><NativeTabs /><NativePush /></>}
      <Navbar />
      <div className={`native-inset ${nativeApp ? "" : "pt-14"}`}>
        <Flash />
        <main className="max-w-[480px] mx-auto px-4 pb-8">{children}</main>
      </div>
    </div>
  )
}

// habits/app/frontend/layouts/Layout.vue
<script setup>
import { usePage } from "@inertiajs/vue3"
import { computed } from "vue"
import { NativeTabs } from "@ruby-native/vue"
import Navbar from "~/components/Navbar.vue"
import Flash from "~/components/Flash.vue"

const page = usePage()
const userSignedIn = computed(() => page.props.user_signed_in)
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <NativeTabs v-if="userSignedIn" />
    <Navbar />
    <div class="pt-12 native-inset">
      <Flash />
      <main class="max-w-lg mx-auto">
        <slot />
      </main>
    </div>
  </div>
</template>
