// vue/app/frontend/pages/Profiles/Show.vue
<script setup>
import { Head, Link, router, usePage } from "@inertiajs/vue3"
import { computed } from "vue"
import { NativeNavbar, NativeButton, NativeMenuItem } from "ruby_native/vue"

const page = usePage()
const nativeApp = computed(() => page.props.nativeApp)

defineProps({
  user: Object,
})

function handleSignOut() {
  router.delete("/session")
}
</script>

<template>
  <Head title="Profile" />
  <NativeNavbar title="Profile">
    <NativeButton position="leading" icon="ellipsis.circle">
      <NativeMenuItem title="Edit profile" href="/profile/edit" icon="pencil" />
      <NativeMenuItem title="Sign out" click="#sign-out-button" icon="rectangle.portrait.and.arrow.right" />
    </NativeButton>
  </NativeNavbar>
  <div class="px-4 pt-6">
    <h1 v-if="!nativeApp" class="text-2xl font-bold text-gray-900">Profile</h1>
    <div class="mt-6 space-y-4">
      <div>
        <p class="text-sm text-gray-500">Name</p>
        <p class="text-base text-gray-900">{{ user.name || "Not set" }}</p>
      </div>
      <div>
        <p class="text-sm text-gray-500">Email</p>
        <p class="text-base text-gray-900">{{ user.email }}</p>
      </div>
    </div>

    <div :class="nativeApp ? 'native-hidden' : 'mt-8 space-y-3'">
      <Link
        href="/profile/edit"
        class="block w-full text-center bg-indigo-600 text-white rounded-lg px-4 py-2.5 font-medium hover:bg-indigo-700 transition-colors"
      >
        Edit profile
      </Link>
      <button
        id="sign-out-button"
        @click="handleSignOut"
        class="w-full text-red-600 text-sm font-medium py-2 hover:text-red-700 transition-colors"
      >
        Sign out
      </button>
    </div>
  </div>
</template>

// coffee/app/frontend/pages/Categories/Show.jsx
import { Head, Link, usePage } from "@inertiajs/react"
import { NativeNavbar, NativeButton } from "ruby_native/react"

export default function Show({ category, products }) {
  const { nativeApp } = usePage().props

  return (
    <>
      <Head title={category.name} />
      <NativeNavbar title={category.name}>
        <NativeButton icon="bag" href="/cart" />
      </NativeNavbar>

      <div className="mt-4">
        {!nativeApp && <h1 className="text-2xl font-bold text-coffee-800 dark:text-coffee-100">{category.name}</h1>}
        <div className="mt-4 space-y-2">
          {products.map((product) => (
            <Link
              key={product.id}
              href={`/menu/${category.id}/items/${product.id}`}
              className="flex items-center gap-3 p-3 rounded-2xl bg-white dark:bg-coffee-800 shadow-sm hover:shadow-md transition"
            >
              {product.image_url ? (
                <img src={product.image_url} alt={product.name} className="w-16 h-16 rounded-xl object-cover shrink-0" />
              ) : (
                <div className="w-16 h-16 rounded-xl bg-coffee-200 dark:bg-coffee-700 shrink-0" />
              )}
              <div className="flex-1 min-w-0">
                <h2 className="text-sm font-semibold text-coffee-800 dark:text-coffee-100">{product.name}</h2>
                <p className="text-xs text-coffee-500 dark:text-coffee-400 mt-0.5 line-clamp-2">{product.description}</p>
              </div>
              <span className="text-sm font-semibold text-green-700 dark:text-green-400 shrink-0">{product.display_price}</span>
            </Link>
          ))}
        </div>
      </div>
    </>
  )
}
