// coffee/app/frontend/pages/Accounts/Show.jsx
import { Head, router, usePage } from "@inertiajs/react"
import { NativeNavbar, NativeButton, NativeMenuItem } from "ruby_native/react"

export default function Show({ user }) {
  const { nativeApp } = usePage().props

  function handleSignOut() {
    router.delete("/session")
  }

  return (
    <>
      <Head title="Account" />
      <NativeNavbar title="Account">
        <NativeButton icon="ellipsis.circle">
          <NativeMenuItem title="Edit profile" href="/account/edit" icon="pencil" />
          <NativeMenuItem title="Sign out" click="#sign-out" icon="rectangle.portrait.and.arrow.right" />
        </NativeButton>
      </NativeNavbar>

      <div className="mt-4">
        {!nativeApp && <h1 className="text-2xl font-bold text-coffee-800 dark:text-coffee-100">Account</h1>}

        <div className="mt-4 text-center">
          <div className="w-20 h-20 mx-auto rounded-full bg-coffee-800 dark:bg-coffee-200 flex items-center justify-center">
            <span className="text-2xl font-bold text-white dark:text-coffee-900">
              {user.name?.charAt(0)?.toUpperCase() || user.email.charAt(0).toUpperCase()}
            </span>
          </div>
          <h2 className="mt-3 text-lg font-semibold text-coffee-800 dark:text-coffee-100">{user.name || "Guest"}</h2>
          <p className="text-sm text-coffee-500 dark:text-coffee-400">{user.email}</p>
        </div>

        <div className="mt-6 space-y-2">
          {user.favorite_store && (
            <div className="p-4 rounded-2xl bg-white dark:bg-coffee-800 shadow-sm">
              <p className="text-xs text-coffee-500 dark:text-coffee-400">Favorite store</p>
              <p className="text-sm font-medium text-coffee-800 dark:text-coffee-100 mt-0.5">{user.favorite_store}</p>
            </div>
          )}
          <div className="p-4 rounded-2xl bg-white dark:bg-coffee-800 shadow-sm">
            <p className="text-xs text-coffee-500 dark:text-coffee-400">Reward points</p>
            <p className="text-sm font-medium text-coffee-800 dark:text-coffee-100 mt-0.5">{user.reward_points} points</p>
          </div>
        </div>

        <div className={nativeApp ? "native-hidden" : "mt-6 space-y-3"}>
          <a
            href="/account/edit"
            className="block w-full text-center rounded-xl border-2 border-coffee-200 dark:border-coffee-700 text-coffee-700 dark:text-coffee-300 font-medium py-2.5 hover:bg-coffee-100 dark:hover:bg-coffee-800 transition text-sm"
          >
            Edit profile
          </a>
          <button
            id="sign-out"
            onClick={handleSignOut}
            className="block w-full text-center text-sm text-red-600 dark:text-red-400 font-medium py-2.5 hover:underline"
          >
            Sign out
          </button>
        </div>
      </div>
    </>
  )
}

// vue/app/frontend/pages/Profiles/Show.vue
<script setup>
import { Head, Link, router, usePage } from "@inertiajs/vue3"
import { computed } from "vue"
import { NativeNavbar, NativeButton, NativeMenuItem } from "ruby_native/vue"

const page = usePage()
const nativeApp = computed(() => page.props.nativeApp)

defineProps({
  user: Object,
})

function handleSignOut() {
  router.delete("/session")
}
</script>

<template>
  <Head title="Profile" />
  <NativeNavbar title="Profile">
    <NativeButton position="leading" icon="ellipsis.circle">
      <NativeMenuItem title="Edit profile" href="/profile/edit" icon="pencil" />
      <NativeMenuItem title="Sign out" click="#sign-out-button" icon="rectangle.portrait.and.arrow.right" />
    </NativeButton>
  </NativeNavbar>
  <div class="px-4 pt-6">
    <h1 v-if="!nativeApp" class="text-2xl font-bold text-gray-900">Profile</h1>
    <div class="mt-6 space-y-4">
      <div>
        <p class="text-sm text-gray-500">Name</p>
        <p class="text-base text-gray-900">{{ user.name || "Not set" }}</p>
      </div>
      <div>
        <p class="text-sm text-gray-500">Email</p>
        <p class="text-base text-gray-900">{{ user.email }}</p>
      </div>
    </div>

    <div :class="nativeApp ? 'native-hidden' : 'mt-8 space-y-3'">
      <Link
        href="/profile/edit"
        class="block w-full text-center bg-indigo-600 text-white rounded-lg px-4 py-2.5 font-medium hover:bg-indigo-700 transition-colors"
      >
        Edit profile
      </Link>
      <button
        id="sign-out-button"
        @click="handleSignOut"
        class="w-full text-red-600 text-sm font-medium py-2 hover:text-red-700 transition-colors"
      >
        Sign out
      </button>
    </div>
  </div>
</template>
