// vue/app/frontend/pages/Profiles/Edit.vue
<script setup>
import { Head, useForm, usePage } from "@inertiajs/vue3"
import { computed } from "vue"
import { NativeForm, NativeNavbar, NativeSubmitButton } from "ruby_native/vue"

const page = usePage()
const nativeApp = computed(() => page.props.nativeApp)

const props = defineProps({
  user: Object,
  errors: Array,
})

const form = useForm({
  user: {
    name: props.user.name || "",
    email: props.user.email,
  },
})

function handleSubmit() {
  form.patch("/profile")
}
</script>

<template>
  <Head title="Edit profile" />
  <NativeNavbar title="Edit profile">
    <NativeSubmitButton title="Save" />
  </NativeNavbar>
  <NativeForm />
  <div v-if="!nativeApp" class="px-4 pt-6 pb-4">
    <h1 class="text-2xl font-bold text-gray-900">Edit profile</h1>
  </div>
  <div class="px-4">
    <form @submit.prevent="handleSubmit" class="space-y-6">
      <div v-if="errors?.length > 0" class="bg-red-50 border border-red-200 rounded-lg p-4">
        <p v-for="(error, i) in errors" :key="i" class="text-sm text-red-800">{{ error }}</p>
      </div>

      <div>
        <label for="name" class="block text-sm font-medium text-gray-700 mb-1">
          Name
        </label>
        <input
          id="name"
          type="text"
          v-model="form.user.name"
          class="w-full rounded-lg border border-gray-300 px-3 py-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
        />
      </div>

      <div>
        <label for="email" class="block text-sm font-medium text-gray-700 mb-1">
          Email
        </label>
        <input
          id="email"
          type="email"
          v-model="form.user.email"
          class="w-full rounded-lg border border-gray-300 px-3 py-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
        />
      </div>

      <button
        type="submit"
        :disabled="form.processing"
        :class="nativeApp ? 'hidden' : 'w-full bg-indigo-600 text-white rounded-lg px-4 py-2.5 font-medium hover:bg-indigo-700 disabled:opacity-50 transition-colors'"
      >
        {{ form.processing ? "Saving..." : "Save profile" }}
      </button>
    </form>
  </div>
</template>

// react/app/frontend/pages/Profiles/Edit.jsx
import { Head, useForm, usePage } from "@inertiajs/react"
import { NativeForm, NativeNavbar, NativeSubmitButton } from "ruby_native/react"

export default function Edit({ user, errors }) {
  const { nativeApp } = usePage().props
  const { data, setData, patch, processing } = useForm({
    user: {
      name: user.name || "",
      email: user.email,
    },
  })

  function handleSubmit(e) {
    e.preventDefault()
    patch("/profile")
  }

  return (
    <>
      <Head title="Edit profile" />
      <NativeNavbar title="Edit profile">
        <NativeSubmitButton title="Save" />
      </NativeNavbar>
      <NativeForm />
      {!nativeApp && (
        <div className="px-4 pt-6 pb-4">
          <h1 className="text-2xl font-bold text-gray-900">Edit profile</h1>
        </div>
      )}
      <div className="px-4">
        <form onSubmit={handleSubmit} className="space-y-6">
          {errors?.length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              {errors.map((error, i) => (
                <p key={i} className="text-sm text-red-800">{error}</p>
              ))}
            </div>
          )}

          <div>
            <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
              Name
            </label>
            <input
              id="name"
              type="text"
              value={data.user.name}
              onChange={(e) => setData("user", { ...data.user, name: e.target.value })}
              className="w-full rounded-lg border border-gray-300 px-3 py-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
            />
          </div>

          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">
              Email
            </label>
            <input
              id="email"
              type="email"
              value={data.user.email}
              onChange={(e) => setData("user", { ...data.user, email: e.target.value })}
              className="w-full rounded-lg border border-gray-300 px-3 py-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
            />
          </div>

          <button
            type="submit"
            disabled={processing}
            className={nativeApp ? "hidden" : "w-full bg-indigo-600 text-white rounded-lg px-4 py-2.5 font-medium hover:bg-indigo-700 disabled:opacity-50 transition-colors"}
          >
            {processing ? "Saving..." : "Save profile"}
          </button>
        </form>
      </div>
    </>
  )
}
